# Generated by Django 6.1.1 on 2026-09-11 07:13

import apps.knowledge_base.storage
import django.contrib.postgres.fields
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list)),
                ('language', models.CharField(default='en', max_length=16)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('source_url', models.URLField(blank=True, max_length=2048)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('queued', 'Queued'), ('processing', 'Processing'), ('indexing', 'Indexing'), ('ready', 'Ready'), ('failed', 'Failed'), ('deleting', 'Deleting')], default='uploaded', max_length=16)),
                ('stage', models.CharField(blank=True, choices=[('queued', 'Queued'), ('retrying', 'Waiting to retry'), ('fetching', 'Fetching the page'), ('extracting', 'Extracting text'), ('storing', 'Saving chunks'), ('indexing', 'Embedding and indexing'), ('deleting', 'Removing from the index'), ('done', 'Done')], max_length=16)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error_message', models.TextField(blank=True)),
                ('file_type', models.CharField(blank=True, max_length=16)),
                ('file_size', models.BigIntegerField(default=0)),
                ('chunk_count', models.PositiveIntegerField(default=0)),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('indexed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('queued', 'Queued'), ('processing', 'Processing'), ('indexing', 'Indexing'), ('ready', 'Ready'), ('failed', 'Failed'), ('deleting', 'Deleting')], default='uploaded', max_length=16)),
                ('file', models.FileField(blank=True, max_length=300, storage=apps.knowledge_base.storage.get_storage, upload_to=apps.knowledge_base.storage.version_upload_path)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=127)),
                ('file_size', models.BigIntegerField(default=0)),
                ('checksum', models.CharField(blank=True, db_index=True, max_length=64)),
                ('source_url', models.URLField(blank=True, max_length=2048)),
                ('format', models.CharField(blank=True, max_length=16)),
                ('parser', models.CharField(blank=True, max_length=32)),
                ('extracted_title', models.CharField(blank=True, max_length=300)),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('character_count', models.PositiveIntegerField(default=0)),
                ('chunk_count', models.PositiveIntegerField(default=0)),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('embedding_model', models.CharField(blank=True, max_length=128)),
                ('embedding_dimensions', models.PositiveIntegerField(blank=True, null=True)),
                ('index_generation', models.BigIntegerField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('indexed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='knowledge_base.document')),
            ],
            options={
                'ordering': ('-number',),
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('index', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('content_hash', models.CharField(max_length=64)),
                ('page', models.PositiveIntegerField(blank=True, null=True)),
                ('pages', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, default=list)),
                ('heading', models.CharField(blank=True, max_length=300)),
                ('section', models.CharField(blank=True, max_length=1000)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='knowledge_base.documentversion')),
            ],
            options={
                'ordering': ('index',),
            },
        ),
        migrations.AddField(
            model_name='document',
            name='active_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='knowledge_base.documentversion'),
        ),
        migrations.AddField(
            model_name='document',
            name='latest_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='knowledge_base.documentversion'),
        ),
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('status', models.CharField(choices=[('active', 'Active'), ('deleting', 'Deleting')], default='active', max_length=16)),
                ('chat_enabled', models.BooleanField(default=False)),
                ('default_language', models.CharField(default='en', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='knowledge_bases', to='knowledge_base.workspace')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='document',
            name='knowledge_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='knowledge_base.knowledgebase'),
        ),
        migrations.CreateModel(
            name='KnowledgeSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('file', 'File upload'), ('url', 'Web page'), ('text', 'Text')], max_length=32)),
                ('name', models.CharField(max_length=300)),
                ('url', models.URLField(blank=True, max_length=2048)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('knowledge_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='knowledge_base.knowledgebase')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='document',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='knowledge_base.knowledgesource'),
        ),
        migrations.CreateModel(
            name='RagQueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('test', 'Test RAG'), ('chat', 'Chat')], max_length=8)),
                ('support', models.CharField(blank=True, max_length=32)),
                ('grounded', models.BooleanField(default=False)),
                ('retrieval_count', models.PositiveIntegerField(default=0)),
                ('context_chunks', models.PositiveIntegerField(default=0)),
                ('retrieval_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('rerank_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('generation_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('total_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('provider', models.CharField(blank=True, max_length=64)),
                ('model', models.CharField(blank=True, max_length=128)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('knowledge_base', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='query_logs', to='knowledge_base.knowledgebase')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='knowledge_base.workspace')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='IngestionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('ingest', 'Ingest'), ('reindex', 'Re-index'), ('delete_document', 'Delete document'), ('delete_knowledge_base', 'Delete knowledge base')], max_length=32)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=16)),
                ('stage', models.CharField(choices=[('queued', 'Queued'), ('retrying', 'Waiting to retry'), ('fetching', 'Fetching the page'), ('extracting', 'Extracting text'), ('storing', 'Saving chunks'), ('indexing', 'Embedding and indexing'), ('deleting', 'Removing from the index'), ('done', 'Done')], default='queued', max_length=16)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=3)),
                ('run_after', models.DateTimeField(default=django.utils.timezone.now)),
                ('locked_by', models.CharField(blank=True, max_length=128)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_requested', models.BooleanField(default=False)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error_message', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='knowledge_base.document')),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='knowledge_base.documentversion')),
                ('knowledge_base', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='knowledge_base.knowledgebase')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='knowledge_base.workspace')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=64)),
                ('target_type', models.CharField(max_length=32)),
                ('target_id', models.CharField(max_length=64)),
                ('target_label', models.CharField(blank=True, max_length=300)),
                ('knowledge_base_id_ref', models.UUIDField(blank=True, db_index=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='knowledge_base.workspace')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='WorkspaceMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('editor', 'Editor'), ('viewer', 'Viewer')], default='viewer', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_memberships', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='knowledge_base.workspace')),
            ],
        ),
        migrations.AddConstraint(
            model_name='documentversion',
            constraint=models.UniqueConstraint(fields=('document', 'number'), name='kb_unique_version_number'),
        ),
        migrations.AddConstraint(
            model_name='documentchunk',
            constraint=models.UniqueConstraint(fields=('version', 'index'), name='kb_unique_chunk_index'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['knowledge_base', 'status'], name='kb_document_status'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['knowledge_base', '-updated_at'], name='kb_document_recent'),
        ),
        migrations.AddConstraint(
            model_name='knowledgebase',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('workspace'), condition=models.Q(('status', 'active')), name='kb_unique_active_name_per_workspace'),
        ),
        migrations.AddIndex(
            model_name='ingestionjob',
            index=models.Index(fields=['status', 'run_after'], name='kb_job_claim'),
        ),
        migrations.AddIndex(
            model_name='ingestionjob',
            index=models.Index(fields=['knowledge_base', '-created_at'], name='kb_job_recent'),
        ),
        migrations.AddConstraint(
            model_name='ingestionjob',
            constraint=models.UniqueConstraint(condition=models.Q(('kind__in', ('ingest', 'reindex')), ('status__in', ('queued', 'running'))), fields=('document',), name='kb_one_active_writer_per_document'),
        ),
        migrations.AddConstraint(
            model_name='workspacemembership',
            constraint=models.UniqueConstraint(fields=('workspace', 'user'), name='kb_one_membership_per_user'),
        ),
    ]
